config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  root to: 'pages#home'

  resources :games, only: [:index, :show, :new, :create] do
    resources :trades, only: [:new]
  end

  resources :profiles, only: [:show, :edit, :update]

  resources :trades, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asker_trade_game.rb
AskerTradeGame = TradeGame

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :first_participant, class_name: "User"
  belongs_to :second_participant, class_name: "User"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :owner, class_name: "User"

  validates :name, :nostalgia_point, :platform, presence: true
  validates :nostalgia_point, inclusion: 1..10

  has_many :trade_games, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :content, presence: true
end

app/models/receiver_trade_game.rb
ReceiverTradeGame = TradeGame

app/models/trade.rb
class Trade < ApplicationRecord
  include Abyme::Model

  belongs_to :asker, class_name: "User"
  belongs_to :receiver, class_name: "User"

  has_many :trade_games, dependent: :destroy
  has_many :asker_trade_games, inverse_of: :trade, class_name: "TradeGame"
  has_many :receiver_trade_games, inverse_of: :trade, class_name: "TradeGame"
  has_many :trade_transitions, autosave: false, dependent: :destroy

  abymize :asker_trade_games
  abymize :receiver_trade_games

  include Statesman::Adapters::ActiveRecordQueries[
    transition_class: TradeTransition,
    initial_state: :pending
  ]

  def state_machine
    @state_machine ||= TradeStateMachine.new(self, transition_class: TradeTransition)
  end
end

app/models/trade_game.rb
class TradeGame < ApplicationRecord
  belongs_to :trade
  belongs_to :game

  scope :owner_is, -> (user) { includes(:game).where(games: { owner: user }) }
end

app/models/trade_state_machine.rb
class TradeStateMachine
  include Statesman::Machine

  state :pending, initial: true
  state :one_validated
  state :counter_proposal
  state :refused
  state :two_validated

  transition from: :pending, to: :one_validated
  transition from: :one_validated, to: [:two_validated, :refused, :counter_proposal]
  transition from: :counter_proposal, to: :one_validated
end

app/models/trade_transition.rb
class TradeTransition < ApplicationRecord
  include Statesman::Adapters::ActiveRecordTransition

  # If your transition table doesn't have the default `updated_at` timestamp column,
  # you'll need to configure the `updated_timestamp_column` option, setting it to
  # another column name (e.g. `:updated_on`) or `nil`.
  #
  # self.updated_timestamp_column = :updated_on
  # self.updated_timestamp_column = nil

  belongs_to :trade, inverse_of: :trade_transitions

  validates :to_state, inclusion: { in: TradeStateMachine.states }

  after_destroy :update_most_recent, if: :most_recent?

  private

  def update_most_recent
    last_transition = trade.trade_transitions.order(:sort_key).last
    return unless last_transition.present?
    last_transition.update_column(:most_recent, true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, foreign_key: :owner_id, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :trades, foreign_key: :asker_id, dependent: :destroy
  has_one_attached :avatar

  validates :username, :city, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :city, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :city, :avatar])
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = policy_scope(Game)

    if params[:query]
      @games = @games.where("name ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: "games/partials/games_list.html", locals: { games: @games } }
    end
  end

  def show
    @game = Game.find(params[:id])
    authorize @game
  end

  def new
    @game = Game.new
    authorize @game
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def show
    authorize(:profile, :show?)
  end

  def edit
    authorize(:profile, :edit?)
  end

  def update
    authorize(:profile, :update?)

    if @user.update(user_params)
      UpdateUserJob.perform_later(current_user.id)
      redirect_to profile_path(@user), notice: "Your profile has been updated!"
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :city, :avatar)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    games_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    games_path
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  def show
    @trade = Trade.find(params[:id])
    authorize @trade
  end

  def new
    @trade = Trade.new
    @asker_games = current_user.games
    @game = Game.find(params[:game_id])
    @receiver_games = @game.owner.games
    authorize @trade
  end

  def create
    @trade = Trade.new
    @trade.asker = current_user
    key_game = params.dig(:trade, :receiver_trade_games_attributes).keys.first
    @game = Game.find(params.dig(:trade, :receiver_trade_games_attributes).dig(key_game, :game))
    @trade.receiver = @game.owner
    authorize @trade

    if @trade.save
      # This line doesn't work at all
      @trade.asker_trade_games.create!(trade_params)
      redirect_to trade_path(@trade)
    else
      flash[:alert] = "Something went wrong, please contact us"
      render "games/show"
    end
  end

  private

  def trade_params
    params.require(:trade).permit(asker_trade_games_attributes: [:id, :game, :_destroy],
                                  receiver_trade_games_attributes: [:id, :game, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abyme/_asker_game_fields.html.erb
<%= f.input :game %>
<%= f.hidden_field :_destroy %>

<%= remove_associated_record(tag: :div) do %>
  <i class="fas fa-trash"></i>
<% end %>

<%#= , selected: @receiver_games, collection: @receiver_games %>

app/views/abyme/_asker_trade_game_fields.html.erb
<%= f.input :game, selected: @asker_games, collection: @asker_games %>
<%= f.hidden_field :_destroy %>

<%= remove_associated_record(tag: :div) do %>
  <i class="fas fa-trash"></i>
<% end %>

app/views/abyme/_receiver_game_fields.html.erb
<%= f.input :game %>
<%= f.hidden_field :_destroy %>

<%= remove_associated_record(tag: :div) do %>
  <i class="fas fa-trash"></i>
<% end %>

<%#= , selected: @receiver_games, collection: @receiver_games %>

app/views/abyme/_receiver_trade_game_fields.html.erb
<%= f.input :game, selected: @receiver_games, collection: @receiver_games %>
<%= f.hidden_field :_destroy %>

<%= remove_associated_record(tag: :div) do %>
  <i class="fas fa-trash"></i>
<% end %>

app/views/games/index.html.erb
<div id="games-index" style="background: url('<%= cl_image_path 'gamershare/retro-gaming-home' %>'); background-size: cover; min-height: 100vh;">
  <div data-controller="refresh-games-list">
    <%= form_with url: games_path,
                  method: :get,
                  data: { refresh_games_list_target: "form" },
                  html: { id: "game-search-bar" } do |f| %>
      <%= f.text_field :query,
                      placeholder: "Search a game",
                      data: { refresh_games_list_target: "searchInput",
                      action: "keyup->refresh-games-list#update" } %>
    <% end %>

    <%= render "games/partials/games_list", games: @games %>
  </div>
</div>

app/views/games/partials/_games_list.html.erb
<div data-refresh-games-list-target="list">
  <ul class="d-flex justify-content-around flex-wrap">
    <%= render(GameCardComponent.with_collection(@games)) %>
  </ul>
</div>

app/views/games/partials/_list.html.erb
<div data-refresh-games-list-target="list">
  <ul class="d-flex justify-content-around flex-wrap">
    <%= render(GameCardComponent.with_collection(@games)) %>
  </ul>
</div>

app/views/games/show.html.erb
<div style="padding-top: 70px;">
  <%= @game.name %>
  <%= @game.owner.username %>

  <% unless @game.owner == current_user %>
    <%= link_to "Ask for a trade", new_game_trade_path(@game) %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamershare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render NavbarComponent.new(user: current_user) %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div style="background: url('<%= cl_image_path 'gamershare/retro-gaming-home' %>'); background-size: cover; height: 100vh;">
</div>

app/views/profiles/edit.html.erb
<div style="padding-top: 100px;">
  <%= simple_form_for @user, url: profile_path(@user), method: :patch do |f| %>
    <%= f.input :email %>
    <%= f.input :username %>
    <%= f.input :city %>
    <%= f.input :avatar, as: :file %>
    <%= f.submit "Update my profile" %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div style="padding-top: 100px;">
  <h1><%= @user.username %></h1>
  <p><%= "My city: #{@user.city}" %></p>
  <p><%= "My nostalgia points: #{@user.total_nostalgia}" %></p>
  <%= link_to "Edit my profile", edit_profile_path, class: "btn btn-secondary mt-4" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/trades/new.html.erb
<div id="trades-new" style="background: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.5)), url('<%= cl_image_path 'gamershare/retro-gaming-trade' %>'); background-size: cover; min-height: 100vh;">

  <h1>What games do you want to trade?</h1>

  <%= render "trades/partials/trade_form", trade: @trade %>
</div>

app/views/trades/partials/_trade_form.html.erb
<%= simple_form_for @trade do |f| %>
  <%= f.abyme_for(:asker_trade_games) do |abyme| %>
    <%= abyme.records %>
    <%= abyme.new_records %>
    <%= add_associated_record(content: "Add game from my collection",
                              html: {class: "btn btn-secondary"}) %>
  <% end %>

  <%= f.abyme_for(:receiver_trade_games) do |abyme| %>
    <%= abyme.records %>
    <%= abyme.new_records %>
    <%= add_associated_record(content: "Add game from #{@game.owner.username}'s collection",
                              html: {class: "btn btn-secondary"}) %>
  <% end %>

  <%= f.submit class: "new_trade__submit btn btn-primary" %>
<% end %>

app/views/trades/show.html.erb
<div style="padding-top: 100px; background: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.5)), url('<%= cl_image_path 'gamershare/retro-gaming-trade' %>'); background-size: cover; min-height: 100vh;">
  <% @trade.trade_games.each do |trade_game| %>
    <p class="text-white"><%= trade_game.game.name %></p>
  <% end %>
</div>